version: '3.8'

services:
  mysqldb:
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootchatbot
      MYSQL_USER: cpechatbot
      MYSQL_PASSWORD: chitchat
      MYSQL_DATABASE: cpechatbotdb
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - 'storage_data:/mysql'

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - 'storage_data:/redis'

volumes:
  storage_data:
    driver: local
