version: '3.8'

services:
  mysqldb:
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootchatbot
      MYSQL_USER: cpechatbot
      MYSQL_PASSWORD: chitchat
      MYSQL_DATABASE: cpechatbotdb
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-tier

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - app-tier

  backend-api:
    depends_on:
      - mysqldb
      - redis
    build: .
    ports:
      - '3000:3000'
    env_file: .production.env
    networks:
      - app-tier

volumes:
  db_data:
    driver: local

networks:
  app-tier:
    driver: bridge
