version: '3'

services:
  mysqldb:
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootchatbot
      MYSQL_USER: cpechatbot
      MYSQL_PASSWORD: chitchat
      MYSQL_DATABASE: cpechatbotdb
    ports:
      - '3306:3306'
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
